version: '4'
services:
  frontend:
    build: ./wbb-analytics
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
  backend:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"
